import "./globals.css";

export const metadata = {
  title: "Demo App For City Police",
  description:
    "Generated by create next app demo app for city police app this is made by me",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
